# .github/workflows/terraform.yaml

name: 'Terraform-TF100-Deploy'

on:
  push:
   branches:
    - main
   paths:
    - /src/terraform/**

  pull_request:
    branches:
    - main
    paths:
    - /src/terraform/**

  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  TF_PATH: '${{github.workspace}}/src/terraform'

jobs:
  terraformPlan:
    runs-on: ubuntu-latest
    name: TerraformPlan
    environment: TF100

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.TF_PATH }}

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ${{ env.TF_PATH }}

    - name: Terraform Plan
      run: terraform plan
      working-directory: ${{ env.TF_PATH }}